FROM mambaorg/micromamba:latest

USER root

# Install procps so 'ps' is available for Nextflow
RUN apt-get update && apt-get install -y procps && rm -rf /var/lib/apt/lists/*

# Create environment and install tools from conda-forge and bioconda
RUN micromamba create -y -n autocycler -c conda-forge -c bioconda \
      python=3.12 curl pip && \
    micromamba run -n autocycler micromamba install -y -c conda-forge -c bioconda \
      just poetry ripgrep \
      canu=2.3 \
      flye metamdbg miniasm minimap2 minipolish necat nextdenovo nextpolish \
      unicycler racon raven-assembler wtdbg any2fasta mash seqtk chopper \
      fastp=1.0.1 libdeflate=1.23 dnaapler myloasm && \
    micromamba clean --all --yes

# Install latest plassembler from PyPI (not Bioconda!)
RUN micromamba run -n autocycler pip install plassembler

RUN micromamba run -n autocycler bash -c "\
  export PLASSEMBLER_DB=/opt/conda/envs/autocycler/plassembler_db && \
  mkdir -p \$PLASSEMBLER_DB && \
  plassembler download -d \$PLASSEMBLER_DB --force"

# Add the autocycler environment to PATH.
ENV PATH="/opt/conda/envs/autocycler/bin:$PATH"
ENV PLASSEMBLER_DB="/opt/conda/envs/autocycler/plassembler_db"
ENV TERM=xterm-256color

# Autocycler version to install
ENV AUTO_CYCLER_VERSION=0.5.2

# Download and install latest release of Autocycler
RUN curl -L -o autocycler.tar.gz \
      https://github.com/rrwick/Autocycler/releases/download/v${AUTO_CYCLER_VERSION}/autocycler-linux-x86_64-gnu-v${AUTO_CYCLER_VERSION}.tar.gz && \
    tar -xzf autocycler.tar.gz && \
    mv autocycler /opt/conda/envs/autocycler/bin/ && \
    rm autocycler.tar.gz
    
# Default command
CMD ["/bin/sh", "-c", "autocycler --help"]
