FROM continuumio/miniconda3:latest

LABEL maintainer="jimmy_12222@hotmail.com"
LABEL description="AGAT >=1.6 + bioinformatics tools (samtools, bedtools, gffread)"

SHELL ["/bin/bash", "-c"]

RUN conda config --set channel_priority strict && \
    conda config --add channels defaults && \
    conda config --add channels bioconda && \
    conda config --add channels conda-forge && \
    conda create -y -n agat_env \
        agat=1.6.0 \
        samtools \
        bedtools \
        gffread && \
    conda clean -afy

ENV PATH=/opt/conda/envs/agat_env/bin:$PATH
ENV CONDA_DEFAULT_ENV=agat_env

WORKDIR /data
CMD [ "bash" ]